# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Build docker image
    #   run: docker build -t gabardomateus/web-crawler-scheduler .
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: web-crawler-scheduler:latest
        outputs: type=docker,dest=/tmp/web-crawler-scheduler.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-crawler-scheduler
        path: /tmp/web-crawler-scheduler.tar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: web-crawler-scheduler
        path: /tmp
    - name: Load image
      run: |
        docker load --input /tmp/web-crawler-scheduler.tar
        docker image ls -a  
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push docker image
      run:  docker push gabardomateus/web-crawler-scheduler    
